services:
  sql:
    container_name: "sql"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "mBT7OQ7RBW41FAPwucxTdc"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "sql"
    volumes:
    - "pocdockerfilesql-apphost-sql-data:/var/opt/mssql"
    ports:
    - target: 1433
      published: 1433
    restart: unless-stopped
  apiservice:
    container_name: "apiservice"
    build:
      dockerfile: Dockerfile-Api
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__sqldb: "Server=sql,1433;User ID=sa;Password=mBT7OQ7RBW41FAPwucxTdc;TrustServerCertificate=true;Database=sqldb"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "apiservice"
    ports:
    - target: 8081
      published: 10000
    - target: 8444
      published: 10001
    restart: unless-stopped
  webfrontend:
    container_name: "webfrontend"
    build:
      dockerfile: Dockerfile-Web
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      services__apiservice__http__0: "http://apiservice:8081"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "webfrontend"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
volumes:
  pocdockerfilesql-apphost-sql-data: {}
